# Generated by Django 6.0.1 on 2026-01-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReqSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('url', models.URLField()),
                ('time_request', models.TimeField()),
                ('time_response', models.TimeField()),
                ('duration', models.DurationField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
