# Generated by Django 6.0.1 on 2026-01-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_alter_reqsite_active_alter_reqsite_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqsite',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В процессе'), ('done', 'Завершен'), ('error', 'Ошибка')], default='new', max_length=15),
        ),
        migrations.AlterField(
            model_name='reqsite',
            name='time_response',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
